### ISSUE TITLE
Delay is not working

### ISSUE THREAD

**Issue by thiagorossener** [weareferal/scrollxp#18]
The attribute `data-animate-delay` is not working.

**Comment by mindfullsilence** [comment]
Seeing the same for stagger, have tried both ways to get sequential elements to offset each other. Is there a current workaround?

**Comment by thiagorossener** [comment]
Hey there. No, there isn't, but should be easy to implement the function, it's just not implemented at the moment.

**Comment by thiagorossener** [comment]
Fixed on version 2.1.1.
