### ISSUE TITLE
trigger multiple animations at same time

### ISSUE THREAD

**Issue by samuelbirch** [weareferal/scrollxp#30]
Is there a way within a scene to trigger all the animations to start at the same time or a way to overlap them?

**Comment by thiagorossener** [comment]
@samuelbirch sorry for taking a whole year!

Yes, there is. It's in the documentation here:
https://github.com/weareferal/scrollxp/blob/master/docs/animation/animation-properties.md#position

> **Note:** By default, all scenes start with the label `start`. So, if you want all the animations run at the same time, just add `data-animate-position="start"` to them.
