### ISSUE TITLE
Parallax not smooth on mobile devices

### ISSUE THREAD

**Issue by moritzebeling** [weareferal/scrollxp#51]
Hello, thank you for developing ScrollXP!

I want to create a parallax effect for a few (<10) elements like
```html
<div class="parallax"
    data-animate
    data-animate-from-y="100"
    data-animate-to-y="-100">
```
but unfortunately it is not really smooth. On desktop (M1) it animates *almost* smooth, but on a smartphone (iPhone 13) it flickers and stutters a bit, on iPhone X so heavily that the page feels broken.
I don’t use any other animations and transitions that could interfere.

What am I doing wrong? Is there a piece I am missing?
Thank you for any advice!

**Comment by thiagorossener** [comment]
Hey @moritzebeling, glad you're enjoying the lib!

Parallax animations don't work with `data-animate`, they work with `data-parallax`.

Take a look at [this example](https://codepen.io/weareferal/pen/abmOOwd), it should help you.

**Comment by moritzebeling** [comment]
Hey, thank you very much. Okay, this makes sense as far as the naming goes.
However the stuttering remains and I find it very hard to control. I might try GSAP directly. Thank you!
